# BabyShield Mobile - CI/CD Workflow
# Linting, Testing, and Build Verification
# Triggers on: Pull Requests and Pushes to main/develop

name: Mobile CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

# Cancel in-progress runs for same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ============================================
  # JOB 1: Linting & Code Quality
  # ============================================
  lint:
    name: ðŸ” Lint & Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ” Run ESLint
        run: npm run lint
        continue-on-error: false

      - name: ðŸ’… Check Prettier formatting
        run: npm run format:check
        continue-on-error: false

      - name: ðŸ”’ Check for security vulnerabilities
        run: npm audit --audit-level=high
        continue-on-error: true

  # ============================================
  # JOB 2: TypeScript Type Checking
  # ============================================
  typecheck:
    name: ðŸ“˜ TypeScript Type Check
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ”Ž Run TypeScript compiler
        run: npm run typecheck

  # ============================================
  # JOB 3: Unit & Integration Tests
  # ============================================
  test:
    name: ðŸ§ª Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ§ª Run unit tests
        run: npm run test:ci

      - name: ðŸ“Š Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: mobile
          name: mobile-coverage
          fail_ci_if_error: false

  # ============================================
  # JOB 4: Build Verification (Android)
  # ============================================
  build-android:
    name: ðŸ¤– Build Android
    runs-on: ubuntu-latest
    needs: [lint, typecheck]

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: â˜• Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ”¨ Build Android APK (Debug)
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon

      - name: ðŸ“¤ Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7

  # ============================================
  # JOB 5: Build Verification (iOS)
  # ============================================
  build-ios:
    name: ðŸŽ Build iOS
    runs-on: macos-latest
    needs: [lint, typecheck]

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ’Ž Install CocoaPods
        run: |
          cd ios
          pod install --repo-update

      - name: ðŸ”¨ Build iOS (Debug)
        run: |
          cd ios
          xcodebuild -workspace BabyShield.xcworkspace \
            -scheme BabyShield \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            clean build \
            CODE_SIGNING_ALLOWED=NO

  # ============================================
  # JOB 6: API Integration Tests
  # ============================================
  api-integration:
    name: ðŸ”Œ API Integration Tests
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: ðŸ“¦ Install dependencies
        run: npm ci

      - name: ðŸ”Œ Test API connectivity
        run: npm run test:api
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL_STAGING }}
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}

  # ============================================
  # JOB 7: Security Scan
  # ============================================
  security:
    name: ðŸ”’ Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ”’ Run Snyk security scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  # ============================================
  # JOB 8: PR Size Check
  # ============================================
  pr-size:
    name: ðŸ“ Check PR Size
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: ðŸ“ Check PR size
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const additions = pr.additions;
            const deletions = pr.deletions;
            const total = additions + deletions;

            if (total > 1000) {
              core.setFailed(`PR is too large (${total} lines). Consider splitting into smaller PRs.`);
            } else if (total > 500) {
              core.warning(`PR is large (${total} lines). Consider reviewing carefully.`);
            }

  # ============================================
  # JOB 9: Success Notification
  # ============================================
  notify-success:
    name: âœ… Notify Success
    runs-on: ubuntu-latest
    needs: [lint, typecheck, test, build-android, build-ios]
    if: success()

    steps:
      - name: âœ… All checks passed
        run: |
          echo "ðŸŽ‰ All CI checks passed successfully!"
          echo "âœ… Linting: Passed"
          echo "âœ… Type checking: Passed"
          echo "âœ… Tests: Passed"
          echo "âœ… Android build: Passed"
          echo "âœ… iOS build: Passed"
