# Codecov configuration for BabyShield Backend
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        # Minimum coverage required
        target: 80%
        threshold: 1%
        base: auto
        
    patch:
      default:
        # Coverage for new code in PRs
        target: 85%
        threshold: 0%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
  
ignore:
  - "tests/**/*"
  - "scripts/**/*"
  - "docs/**/*"
  - "**/__pycache__/**/*"
  - "**/migrations/**/*"
  - "setup.py"
  - "alembic/**/*"
  
flags:
  unittests:
    paths:
      - "api/"
      - "core_infra/"
      - "utils/"
    carryforward: true
    
  integration:
    paths:
      - "api/"
      - "core_infra/"
    carryforward: true
