# Production Environment Configuration
# Optimized settings for production deployment

app:
  name: "BabyShield Backend"
  debug: false
  reload: false
  log_level: "INFO"

server:
  host: "0.0.0.0"
  port: 8001

database:
  # Production MUST use PostgreSQL with psycopg v3
  url: "${DATABASE_URL:-postgresql+psycopg://user:password@db:5432/babyshield}"
  echo: false

security:
  secret_key: "${SECRET_KEY}"
  token_expire_minutes: 15

cors:
  origins:
    - "https://yourdomain.com"
    - "https://www.yourdomain.com"
    - "https://api.yourdomain.com"

uploads:
  directory: "/app/uploads"
  max_size_mb: 10

ai:
  model_cache_dir: "/app/models"
  openai_api_key: "${OPENAI_API_KEY}"

rate_limiting:
  enabled: true
  requests_per_minute: 100
  period_seconds: 60

monitoring:
  enabled: true
  metrics_port: 9090

workers:
  broker_url: "${CELERY_BROKER_URL:-redis://redis:6379/0}"
  result_backend: "${CELERY_RESULT_BACKEND:-redis://redis:6379/0}"

security_headers:
  ssl_redirect: true
  hsts_seconds: 31536000
  hsts_include_subdomains: true
  frame_deny: true
  content_type_nosniff: true

trusted_hosts:
  - "yourdomain.com"
  - "www.yourdomain.com"
