# This is the modified content of the file

# All lines above remain unchanged
# ...
# (assumed existing lines)

# Modified Lines
line 43: token=$(echo "$resp" | python - <<'PY'
line 45: d=json.load(sys.stdin)

# All lines below remain unchanged
# ...
