name: CI (smoke, scheduled)

on:
  schedule:
    - cron: "0 * * * *"   # hourly
  workflow_dispatch:

jobs:
  smoke-account-deletion:
    uses: ./.github/workflows/ci.yml
    with: {}
    secrets: inherit
