name: CI
on:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTEST_ADDOPTS: "--capture=no -q"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest; fi
      - name: Run unit-like tests
        run: |
          if [ -d tests ]; then
            pytest -k "not live and not deployment and not ingest and not ingestion and not celery and not e2e"
          else
            echo "No tests/ directory; skipping tests."
          fi
