name: CI (smoke)
on:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
      PYTEST_ADDOPTS: "-q"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install pytest only
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run isolated smoke test file
        run: |
          pytest -c /dev/null ci_smoke/test_ci_smoke.py

  smoke-account-deletion:
    name: Smoke — Account Deletion
    runs-on: windows-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    env:
      BASE: https://babyshield.cureviax.ai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify token secret present
        shell: pwsh
        run: |
          if (-not "${{ secrets.BSMOKE_TOKEN_FRESH }}") { Write-Error "Missing secret BSMOKE_TOKEN_FRESH"; exit 1 }

      - name: Run smoke_account_deletion.ps1
        shell: pwsh
        run: |
          ./scripts/smoke_account_deletion.ps1 -BASE "$env:BASE" -TOKEN_FRESH "${{ secrets.BSMOKE_TOKEN_FRESH }}"