name: Code Quality

on:
  push:
    branches: [ main, development, staging ]
  pull_request:
    branches: [ main, development, staging ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff mypy bandit safety
          if [ -f config/requirements/requirements.txt ]; then pip install -r config/requirements/requirements.txt; fi
      
      - name: Format check with Black
        run: |
          black --check --diff --color .
      
      - name: Lint with Ruff
        run: |
          ruff check . --output-format=github
      
      - name: Type check with MyPy
        run: |
          mypy api/ core_infra/ agents/ workers/ --ignore-missing-imports --no-strict-optional
        continue-on-error: true
      
      - name: Security check with Bandit
        run: |
          bandit -r api/ core_infra/ agents/ workers/ -f json -o bandit-report.json
          bandit -r api/ core_infra/ agents/ workers/ -f screen
        continue-on-error: true
      
      - name: Dependency vulnerability check
        run: |
          safety check --json --output safety-report.json || true
          safety check || true
        continue-on-error: true
      
      - name: Upload security reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
          retention-days: 30

  complexity-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install radon
        run: pip install radon
      
      - name: Check cyclomatic complexity
        run: |
          radon cc api/ core_infra/ agents/ workers/ -a -nb
      
      - name: Check maintainability index
        run: |
          radon mi api/ core_infra/ agents/ workers/ -nb

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.repository_owner == 'BabyShield' && github.event.repository.private == false
    steps:
      - uses: actions/checkout@v4
      
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
